name: ProtocolSupportUpdater
main: io.WINGS.ProtocolSupportUpdater.Main
version: 1.9
author: WINGS7
website: https://github.com/WINGS07/ProtocolSupportUpdater or https://www.spigotmc.org/resources/protocolsupportupdater.85448/
description: 'This plugin can update ProtocolSupport.'
load: STARTUP
loadbefore: [ProtocolSupport]

commands:
    psu:
        usage: /<command> u/h/su
        description: update or help main command.
        aliases: [protocolsupportupdater]

permissions:
  wings.psu.upd:
    description: Allows update protocolsupport.
    default: op
  wings.psu.help:
    description: Allows get help.
    default: op